### ISSUE TITLE
Complete step object definition.

### ISSUE THREAD

**Issue by Traap** [Traap/amber#11]
The example below shows a fully-qualified test-case expressed in yaml syntax.

```yaml
case:
  name: First Test Case
  purpose: Demonstrate requirement 123 is met.
  requirement: 123
  steps:
    - confirm: Program echo has installed.
      expectation: echo installation location is displayed.
      sudo: true
      command: which
      argument: echo
      evidence: n/a | Starts on next line. | Screen capture starts on next line.
```
