### ISSUE TITLE
Support nested Test Plans, Test Suites, and Test Cases.

### ISSUE THREAD

**Issue by Traap** [Traap/amber#82]
Test Input Factory will support the following structural changes.
```
factory
  plan
    initial
    regression
  suite
    initial
    regression
  case
    initial
     about
     setup
   regression
     bug_fix_001
     bug_fix_002
```

YAML naming convention is applied to each terminus node.  I will illustrate with case/regression/bug_fix_001.  The directory structure and YAML file name shall be:

```
factory/case/regression/bug_fix_001/bug_fix_001.yaml
```

A new YAML operator *folder* is added to the Test Plan, Test Suite, and Test Case object.  Well-formed YAML files are written as follows:

Sample Test Plan
```
plan:
  name: ${file}
  purpose: Write the purpose of this Test Plan.  LaTeX syntax may be used.
includes:
  - folder: regression
     - suites:
        - name: regression
```

Sample Test Suite
```
plan:
  name: ${file}
  purpose: Write the purpose of this Test Suite.  LaTeX syntax may be used.
includes:
  - folder: regression
    - suites:
       - name bug_fix_002       
       - name bug_fix_001
```

This change does not change how Input Factories are currently defined.
